/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedClaimVaultInstruction,
  type ParsedCloseVaultInstruction,
  type ParsedInitializeVaultInstruction,
  type ParsedProofOfLifeInstruction,
} from '../instructions';

export const PROOF_POL_PROGRAM_ADDRESS =
  'DHHHbFFGWX2y4HkgdePB61bUZxdJQw8VmfGvgR4cxeof' as Address<'DHHHbFFGWX2y4HkgdePB61bUZxdJQw8VmfGvgR4cxeof'>;

export enum ProofPolAccount {
  CommitmentVault,
  OwnerProfile,
}

export function identifyProofPolAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): ProofPolAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([14, 195, 87, 111, 213, 201, 5, 129])
      ),
      0
    )
  ) {
    return ProofPolAccount.CommitmentVault;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([51, 38, 236, 107, 38, 26, 62, 91])
      ),
      0
    )
  ) {
    return ProofPolAccount.OwnerProfile;
  }
  throw new Error(
    'The provided account could not be identified as a proofPol account.'
  );
}

export enum ProofPolInstruction {
  ClaimVault,
  CloseVault,
  InitializeVault,
  ProofOfLife,
}

export function identifyProofPolInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): ProofPolInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([87, 111, 176, 185, 53, 172, 227, 137])
      ),
      0
    )
  ) {
    return ProofPolInstruction.ClaimVault;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([141, 103, 17, 126, 72, 75, 29, 29])
      ),
      0
    )
  ) {
    return ProofPolInstruction.CloseVault;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([48, 191, 163, 44, 71, 129, 63, 164])
      ),
      0
    )
  ) {
    return ProofPolInstruction.InitializeVault;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([52, 157, 123, 29, 44, 147, 143, 234])
      ),
      0
    )
  ) {
    return ProofPolInstruction.ProofOfLife;
  }
  throw new Error(
    'The provided instruction could not be identified as a proofPol instruction.'
  );
}

export type ParsedProofPolInstruction<
  TProgram extends string = 'DHHHbFFGWX2y4HkgdePB61bUZxdJQw8VmfGvgR4cxeof',
> =
  | ({
      instructionType: ProofPolInstruction.ClaimVault;
    } & ParsedClaimVaultInstruction<TProgram>)
  | ({
      instructionType: ProofPolInstruction.CloseVault;
    } & ParsedCloseVaultInstruction<TProgram>)
  | ({
      instructionType: ProofPolInstruction.InitializeVault;
    } & ParsedInitializeVaultInstruction<TProgram>)
  | ({
      instructionType: ProofPolInstruction.ProofOfLife;
    } & ParsedProofOfLifeInstruction<TProgram>);
