[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
proof_pol = "aosGKFX4wB17YnkDjrCTyE4imXXadnwjxe2jsYWEY4e"

[programs.devnet]
proof_pol = "aosGKFX4wB17YnkDjrCTyE4imXXadnwjxe2jsYWEY4e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize_vault.ts tests/close.ts tests/claim.ts tests/proof_life.ts tests/proof_pol.ts"
