/**
 *  Proof-of-Life — Permissionless Keeper Bot  (DEVNET)
 *
 * WHAT THIS BOT DOES
 * 
 * Every 2 days it:
 *   1. Fetches every active CommitmentVault on devnet
 *   2. Checks if  now  >  vault.deadline + 2-day grace period
 *   3. If YES → calls claim_vault  →  tokens land in nominee's wallet
 *   4. The keeper earns the vault account rent as reward
 *
 * SECURITY NOTE
 * The keeper has ZERO financial power.
 * The on-chain program always sends tokens to vault.nominee.
 * The keeper only decides WHEN to pull the trigger, never WHERE funds go.
 * If the deadline hasn't passed, the program rejects the call automatically.
 *
 * SETUP
 * -----
 *   1. Generate a keeper wallet:
 *        solana-keygen new --outfile keeper-wallet.json
 *
 *   2. Airdrop SOL on devnet:
 *        solana airdrop 1 $(solana-keygen pubkey keeper-wallet.json) --url devnet
 *
 *   3. Set the env variable (the keypair JSON array):
 *        export KEEPER_KEYPAIR="$(cat keeper-wallet.json)"
 *        export RPC_URL="https://api.devnet.solana.com"   # optional
 *
 *   4. Run:
 *        ts-node keeper/keeper.ts
 */

import * as anchor from "@coral-xyz/anchor";
import {
  Keypair,
  Connection,
  PublicKey,
  SystemProgram,
  SYSVAR_INSTRUCTIONS_PUBKEY,
} from "@solana/web3.js";
import {
  getAssociatedTokenAddressSync,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} from "@solana/spl-token";

// Load the Anchor IDL (generated by `anchor build`)
// eslint-disable-next-line @typescript-eslint/no-var-requires
const IDL = require("../target/idl/proof_pol.json");

//  Configuration 

/** Solana devnet RPC.  Override with  export RPC_URL="https://..."  */
const RPC_URL = process.env.RPC_URL ?? "https://api.devnet.solana.com";

/**
 * How often the bot scans for claimable vaults.
 * Set to 2 days (matches the on-chain CLAIM_GRACE_PERIOD).
 * The first scan always runs immediately on startup.
 */
const POLL_INTERVAL_MS = 2 * 24 * 60 * 60 * 1000; // 48 hours

/**
 * Must match  CLAIM_GRACE_PERIOD  in  programs/.../constants.rs  (172_800s = 2 days).
 * A vault is claimable only when:  now  >=  vault.deadline + CLAIM_GRACE_PERIOD
 */
const CLAIM_GRACE_PERIOD_SECONDS = 172_800;

/** Kamino lending program — still passed as a placeholder account on devnet */
const KAMINO_LENDING_PROGRAM_ID = new PublicKey(
  "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
);

/**
 * Devnet USDC mint (Circle's official devnet USDC).
 * Used to pick the correct placeholder kToken mint on devnet.
 */
const DEVNET_USDC_MINT = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU";

/** Wrapped SOL mint address (same on all clusters) */
const MINT_WSOL = "So11111111111111111111111111111111111111112";

//  Step 1 — Load the keeper's keypair 
/**
 * WHY: The keeper's keypair is the `executor` account in claim_vault.
 *   - It signs every transaction
 *   - It pays the tx fee (~0.000005 SOL)
 *   - It earns the vault account rent back (~0.002 SOL) as reward
 *   - Net cost per claim ≈ 0 on devnet
 *
 * The keypair is stored as a JSON array in the KEEPER_KEYPAIR env variable.
 * This is the same format that `solana-keygen new --outfile wallet.json` produces.
 */
function loadKeeperKeypair(): Keypair {
  const raw = process.env.KEEPER_KEYPAIR;
  if (!raw) {
    throw new Error(
      "\n\nKEEPER_KEYPAIR env variable not set.\n" +
        "Generate a wallet: solana-keygen new --outfile keeper-wallet.json\n" +
        "Then set it:       export KEEPER_KEYPAIR=\"$(cat keeper-wallet.json)\"\n"
    );
  }
  try {
    // Expects a JSON array like [12, 45, 67, ...]
    const arr: number[] = JSON.parse(raw);
    return Keypair.fromSecretKey(Uint8Array.from(arr));
  } catch {
    throw new Error(
      "Could not parse KEEPER_KEYPAIR.\n" +
        "It must be a JSON array of numbers: [12, 45, 67, ...]\n" +
        "Run: export KEEPER_KEYPAIR=\"$(cat keeper-wallet.json)\"\n"
    );
  }
}

//  Step 2 — Devnet kToken placeholder logic 
/**
 * WHY: On devnet, Kamino does NOT exist. But the program's accounts struct
 * always includes a `k_token_mint` and a `vault_k_token_ata`.
 * These two ATAs must have DIFFERENT mints so they don't collide.
 *
 * Rule: if the vault is staking USDC, the kToken placeholder = wSOL.
 *       if the vault is staking anything else, the kToken placeholder = USDC.
 *
 * This mirrors the same logic in frontend/src/lib/proof-pol/client.ts.
 */
function getDevnetKTokenMint(stakeMint: string): string {
  return stakeMint === DEVNET_USDC_MINT ? MINT_WSOL : DEVNET_USDC_MINT;
}

//  Step 3 — Claim a single expired vault 
/**
 * WHY: We build the claim_vault transaction manually (not relying on
 * Anchor's auto-resolution) so we have full control over all 18 accounts.
 *
 * On devnet, the 5 Kamino accounts (reserve, market, authority, supply, program)
 * are dummies — they are never actually invoked by the program.
 * The on-chain  #[cfg(feature = "mainnet")]  guard compiles them away on devnet.
 */
async function claimOneVault(
  program: anchor.Program,
  keeper: Keypair,
  vaultAddress: PublicKey,
  vault: {
    owner: PublicKey;
    nominee: PublicKey;
    mint: PublicKey;
    kTokenMint: PublicKey;
    vaultId: anchor.BN;
  }
): Promise<string> {
  // ── Derive the nominee's token ATA ──
  // WHY: The nominee may not have an ATA yet.
  // claim_vault uses  init_if_needed  — Anchor creates it automatically.
  // The keeper pays the ATA rent (~0.002 SOL) but earns it back from vault rent.
  const nomineeAtaPk = getAssociatedTokenAddressSync(
    vault.mint,
    vault.nominee,
    false, // nominee is a regular wallet, not a PDA
    TOKEN_PROGRAM_ID
  );

  // ── Derive the vault's token ATA ──
  // WHY: This is where the staked tokens live on devnet.
  // On mainnet they'd be in Kamino, but we redeem them back here first.
  const vaultAtaPk = getAssociatedTokenAddressSync(
    vault.mint,
    vaultAddress,
    true, // allowOwnerOffCurve — vaultAddress is a PDA (off the ed25519 curve)
    TOKEN_PROGRAM_ID
  );

  // ── Determine the kToken mint ──
  // WHY: kTokenMint is stored in vault state at vault creation time.
  // On devnet it's a placeholder (either USDC or wSOL, whichever differs from stake mint).
  // On mainnet it would be the real kUSDC/kSOL mint from Kamino.
  const storedKTokenMint = vault.kTokenMint.toBase58();
  const kTokenMintStr =
    storedKTokenMint === SystemProgram.programId.toBase58()
      ? getDevnetKTokenMint(vault.mint.toBase58()) // fallback if not stored
      : storedKTokenMint;
  const kTokenMintPk = new PublicKey(kTokenMintStr);

  // ── Derive the vault's kToken ATA ──
  // WHY: This ATA holds the Kamino receipt tokens (kUSDC/kSOL) on mainnet.
  // On devnet it exists but stays empty. It was created at vault initialization.
  const vaultKTokenAtaPk = getAssociatedTokenAddressSync(
    kTokenMintPk,
    vaultAddress,
    true,
    TOKEN_PROGRAM_ID
  );

  // ── Devnet Kamino placeholder accounts ──
  // WHY: The accounts struct in claim.rs always requires these fields.
  // On devnet builds (no `mainnet` feature), the program never reads them.
  // We pass SystemProgram as a dummy for readonly accounts
  // and vaultAtaPk as a dummy for the mutable liquidity supply account.
  const kaminoReserve = SystemProgram.programId;
  const kaminoLendingMarket = SystemProgram.programId;
  const kaminoLendingMarketAuthority = SystemProgram.programId;
  const kaminoLiquiditySupply = vaultAtaPk; // mutable placeholder

  // ── Send the claim_vault transaction ──
  const sig = await program.methods
    .claimVault()
    .accounts({
      executor: keeper.publicKey, // our keeper wallet — pays fee, earns vault rent
      nominee: vault.nominee, // receives ALL the tokens
      owner: vault.owner, // vault owner (who missed check-in)
      vault: vaultAddress, // the PDA vault state account
      mint: vault.mint, // SPL token mint (USDC / wSOL / etc.)
      nomineeAta: nomineeAtaPk, // nominee's token ATA (created if needed)
      vaultAta: vaultAtaPk, // vault's token ATA (tokens come from here)
      vaultKTokenAta: vaultKTokenAtaPk, // vault's kToken ATA (empty on devnet)
      kTokenMint: kTokenMintPk, // kToken mint (placeholder on devnet)
      kaminoReserve, // dummy on devnet
      kaminoLendingMarket, // dummy on devnet
      kaminoLendingMarketAuthority, // dummy on devnet
      kaminoLiquiditySupply, // dummy on devnet
      kaminoLendingProgram: KAMINO_LENDING_PROGRAM_ID, // passed but not invoked
      instructionSysvar: SYSVAR_INSTRUCTIONS_PUBKEY, // Kamino requires this sysvar
      tokenProgram: TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
    } as any)
    .signers([keeper])
    .rpc({ commitment: "confirmed" });

  return sig;
}

//  Step 4 — Scan ALL vaults and claim expired ones 
/**
 * WHY: We use  program.account.commitmentVault.all()  which:
 *   - Calls  getProgramAccounts  internally
 *   - Automatically adds the CommitmentVault discriminator filter
 *   - Decodes every account into a typed JavaScript object
 *   - Returns  [{ publicKey, account }]  for every vault
 *
 * Then we filter in-memory for:
 *   - isActive === true  (skip closed/claimed vaults)
 *   - now >= deadline + CLAIM_GRACE_PERIOD_SECONDS
 */
async function scanAndClaim(
  program: anchor.Program,
  keeper: Keypair
): Promise<void> {
  const timestamp = new Date().toISOString();
  console.log(`\n${"─".repeat(60)}`);
  console.log(`[${timestamp}]  Scanning for claimable vaults...`);

  // Fetch every CommitmentVault account on-chain
  const allVaults = await program.account.commitmentVault.all();

  // Filter: only active vaults
  const activeVaults = allVaults.filter((v) => v.account.isActive);

  console.log(
    `Found ${allVaults.length} total vault(s) | ${activeVaults.length} active`
  );

  if (activeVaults.length === 0) {
    console.log("Nothing to do. Sleeping until next scan.");
    return;
  }

  const nowSeconds = Math.floor(Date.now() / 1000);
  let claimed = 0;
  let waiting = 0;
  let failed = 0;

  for (const { publicKey: vaultAddress, account: vault } of activeVaults) {
    const deadlineTs = (vault.deadline as anchor.BN).toNumber();
    const claimableAt = deadlineTs + CLAIM_GRACE_PERIOD_SECONDS;
    const shortAddr = vaultAddress.toBase58().slice(0, 12) + "...";

    // ── Not yet claimable ──
    if (nowSeconds < claimableAt) {
      const secondsLeft = claimableAt - nowSeconds;
      const hoursLeft = Math.floor(secondsLeft / 3600);
      const minsLeft = Math.floor((secondsLeft % 3600) / 60);
      console.log(
        `  WAITING   ${shortAddr}  →  claimable in ${hoursLeft}h ${minsLeft}m`
      );
      waiting++;
      continue;
    }

    // ── Claimable — attempt claim ──
    const claimedAtDate = new Date(claimableAt * 1000).toISOString();
    console.log(
      `  CLAIMING  ${shortAddr}  →  expired at ${claimedAtDate}` +
        `  nominee=${vault.nominee.toBase58().slice(0, 12)}...`
    );

    try {
      const sig = await claimOneVault(program, keeper, vaultAddress, vault as any);
      console.log(
        `  ✓ SUCCESS  sig=${sig.slice(0, 20)}...` +
          `  funds sent to ${vault.nominee.toBase58()}`
      );
      claimed++;
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      // Common expected failures:
      //   VaultInactive          → another keeper already claimed it (race condition, harmless)
      //   ClaimGracePeriodNotPassed → time check mismatch (skip, try next run)
      console.error(`  ✗ FAILED   ${shortAddr}  →  ${msg.split("\n")[0]}`);
      failed++;
    }
  }

  console.log(
    `\nScan complete.  Claimed: ${claimed}  |  Waiting: ${waiting}  |  Failed: ${failed}`
  );
  const nextScanAt = new Date(Date.now() + POLL_INTERVAL_MS).toISOString();
  console.log(`Next scan at: ${nextScanAt}`);
}

//  Entry Point 
async function main(): Promise<void> {
  // ── Load keeper wallet ──
  const keeper = loadKeeperKeypair();

  // ── Set up Anchor provider ──
  // WHY: Anchor needs a Connection (RPC) + Wallet (keypair) to build and send txs.
  // AnchorProvider bundles these together.
  const connection = new Connection(RPC_URL, "confirmed");
  const wallet = new anchor.Wallet(keeper);
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
    preflightCommitment: "confirmed",
  });
  anchor.setProvider(provider);

  // ── Load the program using the IDL ──
  // WHY: The IDL (Interface Definition Language) describes all instructions,
  // accounts, and errors. Anchor uses it to build typed transactions.
  const program = new anchor.Program(IDL, provider);

  // ── Print startup info ──
  console.log("╔══════════════════════════════════════════════╗");
  console.log("║     Proof-of-Life Keeper Bot  (DEVNET)       ║");
  console.log("╚══════════════════════════════════════════════╝");
  console.log(`Keeper wallet : ${keeper.publicKey.toBase58()}`);
  console.log(`RPC           : ${RPC_URL}`);
  console.log(`Program       : ${program.programId.toBase58()}`);
  console.log(`Poll interval : every 2 days (${POLL_INTERVAL_MS / 1000}s)`);
  console.log(`Grace period  : ${CLAIM_GRACE_PERIOD_SECONDS / 3600}h after deadline`);

  // ── Check keeper balance ──
  const balance = await connection.getBalance(keeper.publicKey);
  console.log(`Wallet balance: ${(balance / 1_000_000_000).toFixed(6)} SOL`);

  if (balance < 5_000_000) {
    // Less than 0.005 SOL — might not cover tx fees for multiple claims
    console.warn("\n⚠  LOW BALANCE — airdrop before running:");
    console.warn(
      `   solana airdrop 2 ${keeper.publicKey.toBase58()} --url devnet\n`
    );
  }

  // ── Detect run mode ──
  // WHY: GitHub Actions runs the script once and exits (CI=true is set automatically).
  //      On a local server / pm2, we want it to loop forever every 2 days.
  //
  //   CI mode  →  scan once, then exit  (used by GitHub Actions)
  //   Server mode  →  scan now, then repeat every 2 days forever
  const isCI =
    process.env.CI === "true" || process.argv.includes("--once");

  if (isCI) {
    console.log("Mode: CI / one-shot — will exit after this scan.");
  } else {
    console.log("Mode: server — will loop every 2 days.");
  }

  // ── Run the first scan immediately ──
  await scanAndClaim(program, keeper);

  if (isCI) {
    // GitHub Actions: one scan done, exit cleanly.
    console.log("\nCI run complete. Exiting.");
    process.exit(0);
  }

  // Server mode: set up the 2-day loop.
  setInterval(async () => {
    try {
      await scanAndClaim(program, keeper);
    } catch (err: unknown) {
      // Catch unexpected errors so the loop never dies
      console.error(
        "Unexpected error in scan loop:",
        err instanceof Error ? err.message : String(err)
      );
      console.log("Recovering... next scan in 2 days.");
    }
  }, POLL_INTERVAL_MS);
}

main().catch((err) => {
  console.error("Fatal startup error:", err instanceof Error ? err.message : err);
  process.exit(1);
});
