/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { PROOF_POL_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CLOSE_VAULT_DISCRIMINATOR = new Uint8Array([
  141, 103, 17, 126, 72, 75, 29, 29,
]);

export function getCloseVaultDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLOSE_VAULT_DISCRIMINATOR);
}

export type CloseVaultInstruction<
  TProgram extends string = typeof PROOF_POL_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountOwnerAta extends string | AccountMeta<string> = string,
  TAccountVaultAta extends string | AccountMeta<string> = string,
  TAccountVaultKTokenAta extends string | AccountMeta<string> = string,
  TAccountKTokenMint extends string | AccountMeta<string> = string,
  TAccountKaminoReserve extends string | AccountMeta<string> = string,
  TAccountKaminoLendingMarket extends string | AccountMeta<string> = string,
  TAccountKaminoLendingMarketAuthority extends string | AccountMeta<string> =
    string,
  TAccountKaminoLiquiditySupply extends string | AccountMeta<string> = string,
  TAccountKaminoLendingProgram extends string | AccountMeta<string> = string,
  TAccountInstructionSysvar extends string | AccountMeta<string> =
    'Sysvar1nstructions1111111111111111111111111',
  TAccountTokenProgram extends string | AccountMeta<string> =
    'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
    'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountSystemProgram extends string | AccountMeta<string> =
    '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountOwnerAta extends string
        ? WritableAccount<TAccountOwnerAta>
        : TAccountOwnerAta,
      TAccountVaultAta extends string
        ? WritableAccount<TAccountVaultAta>
        : TAccountVaultAta,
      TAccountVaultKTokenAta extends string
        ? WritableAccount<TAccountVaultKTokenAta>
        : TAccountVaultKTokenAta,
      TAccountKTokenMint extends string
        ? ReadonlyAccount<TAccountKTokenMint>
        : TAccountKTokenMint,
      TAccountKaminoReserve extends string
        ? WritableAccount<TAccountKaminoReserve>
        : TAccountKaminoReserve,
      TAccountKaminoLendingMarket extends string
        ? ReadonlyAccount<TAccountKaminoLendingMarket>
        : TAccountKaminoLendingMarket,
      TAccountKaminoLendingMarketAuthority extends string
        ? ReadonlyAccount<TAccountKaminoLendingMarketAuthority>
        : TAccountKaminoLendingMarketAuthority,
      TAccountKaminoLiquiditySupply extends string
        ? WritableAccount<TAccountKaminoLiquiditySupply>
        : TAccountKaminoLiquiditySupply,
      TAccountKaminoLendingProgram extends string
        ? ReadonlyAccount<TAccountKaminoLendingProgram>
        : TAccountKaminoLendingProgram,
      TAccountInstructionSysvar extends string
        ? ReadonlyAccount<TAccountInstructionSysvar>
        : TAccountInstructionSysvar,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseVaultInstructionData = { discriminator: ReadonlyUint8Array };

export type CloseVaultInstructionDataArgs = {};

export function getCloseVaultInstructionDataEncoder(): FixedSizeEncoder<CloseVaultInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_VAULT_DISCRIMINATOR })
  );
}

export function getCloseVaultInstructionDataDecoder(): FixedSizeDecoder<CloseVaultInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseVaultInstructionDataCodec(): FixedSizeCodec<
  CloseVaultInstructionDataArgs,
  CloseVaultInstructionData
> {
  return combineCodec(
    getCloseVaultInstructionDataEncoder(),
    getCloseVaultInstructionDataDecoder()
  );
}

export type CloseVaultAsyncInput<
  TAccountOwner extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountOwnerAta extends string = string,
  TAccountVaultAta extends string = string,
  TAccountVaultKTokenAta extends string = string,
  TAccountKTokenMint extends string = string,
  TAccountKaminoReserve extends string = string,
  TAccountKaminoLendingMarket extends string = string,
  TAccountKaminoLendingMarketAuthority extends string = string,
  TAccountKaminoLiquiditySupply extends string = string,
  TAccountKaminoLendingProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  vault: Address<TAccountVault>;
  mint: Address<TAccountMint>;
  ownerAta?: Address<TAccountOwnerAta>;
  vaultAta?: Address<TAccountVaultAta>;
  vaultKTokenAta?: Address<TAccountVaultKTokenAta>;
  kTokenMint: Address<TAccountKTokenMint>;
  kaminoReserve: Address<TAccountKaminoReserve>;
  kaminoLendingMarket: Address<TAccountKaminoLendingMarket>;
  kaminoLendingMarketAuthority: Address<TAccountKaminoLendingMarketAuthority>;
  kaminoLiquiditySupply: Address<TAccountKaminoLiquiditySupply>;
  kaminoLendingProgram: Address<TAccountKaminoLendingProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getCloseVaultInstructionAsync<
  TAccountOwner extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountOwnerAta extends string,
  TAccountVaultAta extends string,
  TAccountVaultKTokenAta extends string,
  TAccountKTokenMint extends string,
  TAccountKaminoReserve extends string,
  TAccountKaminoLendingMarket extends string,
  TAccountKaminoLendingMarketAuthority extends string,
  TAccountKaminoLiquiditySupply extends string,
  TAccountKaminoLendingProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PROOF_POL_PROGRAM_ADDRESS,
>(
  input: CloseVaultAsyncInput<
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CloseVaultInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PROOF_POL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    ownerAta: { value: input.ownerAta ?? null, isWritable: true },
    vaultAta: { value: input.vaultAta ?? null, isWritable: true },
    vaultKTokenAta: { value: input.vaultKTokenAta ?? null, isWritable: true },
    kTokenMint: { value: input.kTokenMint ?? null, isWritable: false },
    kaminoReserve: { value: input.kaminoReserve ?? null, isWritable: true },
    kaminoLendingMarket: {
      value: input.kaminoLendingMarket ?? null,
      isWritable: false,
    },
    kaminoLendingMarketAuthority: {
      value: input.kaminoLendingMarketAuthority ?? null,
      isWritable: false,
    },
    kaminoLiquiditySupply: {
      value: input.kaminoLiquiditySupply ?? null,
      isWritable: true,
    },
    kaminoLendingProgram: {
      value: input.kaminoLendingProgram ?? null,
      isWritable: false,
    },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.ownerAta.value) {
    accounts.ownerAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.vaultAta.value) {
    accounts.vaultAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.vaultKTokenAta.value) {
    accounts.vaultKTokenAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.kTokenMint.value)),
      ],
    });
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      'Sysvar1nstructions1111111111111111111111111' as Address<'Sysvar1nstructions1111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.ownerAta),
      getAccountMeta(accounts.vaultAta),
      getAccountMeta(accounts.vaultKTokenAta),
      getAccountMeta(accounts.kTokenMint),
      getAccountMeta(accounts.kaminoReserve),
      getAccountMeta(accounts.kaminoLendingMarket),
      getAccountMeta(accounts.kaminoLendingMarketAuthority),
      getAccountMeta(accounts.kaminoLiquiditySupply),
      getAccountMeta(accounts.kaminoLendingProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCloseVaultInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseVaultInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type CloseVaultInput<
  TAccountOwner extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountOwnerAta extends string = string,
  TAccountVaultAta extends string = string,
  TAccountVaultKTokenAta extends string = string,
  TAccountKTokenMint extends string = string,
  TAccountKaminoReserve extends string = string,
  TAccountKaminoLendingMarket extends string = string,
  TAccountKaminoLendingMarketAuthority extends string = string,
  TAccountKaminoLiquiditySupply extends string = string,
  TAccountKaminoLendingProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  vault: Address<TAccountVault>;
  mint: Address<TAccountMint>;
  ownerAta: Address<TAccountOwnerAta>;
  vaultAta: Address<TAccountVaultAta>;
  vaultKTokenAta: Address<TAccountVaultKTokenAta>;
  kTokenMint: Address<TAccountKTokenMint>;
  kaminoReserve: Address<TAccountKaminoReserve>;
  kaminoLendingMarket: Address<TAccountKaminoLendingMarket>;
  kaminoLendingMarketAuthority: Address<TAccountKaminoLendingMarketAuthority>;
  kaminoLiquiditySupply: Address<TAccountKaminoLiquiditySupply>;
  kaminoLendingProgram: Address<TAccountKaminoLendingProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getCloseVaultInstruction<
  TAccountOwner extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountOwnerAta extends string,
  TAccountVaultAta extends string,
  TAccountVaultKTokenAta extends string,
  TAccountKTokenMint extends string,
  TAccountKaminoReserve extends string,
  TAccountKaminoLendingMarket extends string,
  TAccountKaminoLendingMarketAuthority extends string,
  TAccountKaminoLiquiditySupply extends string,
  TAccountKaminoLendingProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PROOF_POL_PROGRAM_ADDRESS,
>(
  input: CloseVaultInput<
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CloseVaultInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountVault,
  TAccountMint,
  TAccountOwnerAta,
  TAccountVaultAta,
  TAccountVaultKTokenAta,
  TAccountKTokenMint,
  TAccountKaminoReserve,
  TAccountKaminoLendingMarket,
  TAccountKaminoLendingMarketAuthority,
  TAccountKaminoLiquiditySupply,
  TAccountKaminoLendingProgram,
  TAccountInstructionSysvar,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PROOF_POL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    ownerAta: { value: input.ownerAta ?? null, isWritable: true },
    vaultAta: { value: input.vaultAta ?? null, isWritable: true },
    vaultKTokenAta: { value: input.vaultKTokenAta ?? null, isWritable: true },
    kTokenMint: { value: input.kTokenMint ?? null, isWritable: false },
    kaminoReserve: { value: input.kaminoReserve ?? null, isWritable: true },
    kaminoLendingMarket: {
      value: input.kaminoLendingMarket ?? null,
      isWritable: false,
    },
    kaminoLendingMarketAuthority: {
      value: input.kaminoLendingMarketAuthority ?? null,
      isWritable: false,
    },
    kaminoLiquiditySupply: {
      value: input.kaminoLiquiditySupply ?? null,
      isWritable: true,
    },
    kaminoLendingProgram: {
      value: input.kaminoLendingProgram ?? null,
      isWritable: false,
    },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      'Sysvar1nstructions1111111111111111111111111' as Address<'Sysvar1nstructions1111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.ownerAta),
      getAccountMeta(accounts.vaultAta),
      getAccountMeta(accounts.vaultKTokenAta),
      getAccountMeta(accounts.kTokenMint),
      getAccountMeta(accounts.kaminoReserve),
      getAccountMeta(accounts.kaminoLendingMarket),
      getAccountMeta(accounts.kaminoLendingMarketAuthority),
      getAccountMeta(accounts.kaminoLiquiditySupply),
      getAccountMeta(accounts.kaminoLendingProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCloseVaultInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseVaultInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedCloseVaultInstruction<
  TProgram extends string = typeof PROOF_POL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    vault: TAccountMetas[1];
    mint: TAccountMetas[2];
    ownerAta: TAccountMetas[3];
    vaultAta: TAccountMetas[4];
    vaultKTokenAta: TAccountMetas[5];
    kTokenMint: TAccountMetas[6];
    kaminoReserve: TAccountMetas[7];
    kaminoLendingMarket: TAccountMetas[8];
    kaminoLendingMarketAuthority: TAccountMetas[9];
    kaminoLiquiditySupply: TAccountMetas[10];
    kaminoLendingProgram: TAccountMetas[11];
    instructionSysvar: TAccountMetas[12];
    tokenProgram: TAccountMetas[13];
    associatedTokenProgram: TAccountMetas[14];
    systemProgram: TAccountMetas[15];
  };
  data: CloseVaultInstructionData;
};

export function parseCloseVaultInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCloseVaultInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 16) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      vault: getNextAccount(),
      mint: getNextAccount(),
      ownerAta: getNextAccount(),
      vaultAta: getNextAccount(),
      vaultKTokenAta: getNextAccount(),
      kTokenMint: getNextAccount(),
      kaminoReserve: getNextAccount(),
      kaminoLendingMarket: getNextAccount(),
      kaminoLendingMarketAuthority: getNextAccount(),
      kaminoLiquiditySupply: getNextAccount(),
      kaminoLendingProgram: getNextAccount(),
      instructionSysvar: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCloseVaultInstructionDataDecoder().decode(instruction.data),
  };
}
