/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { PROOF_POL_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CLOSE_VAULT_DISCRIMINATOR = new Uint8Array([
  141, 103, 17, 126, 72, 75, 29, 29,
]);

export function getCloseVaultDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLOSE_VAULT_DISCRIMINATOR);
}

export type CloseVaultInstruction<
  TProgram extends string = typeof PROOF_POL_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountOwnerAta extends string | AccountMeta<string> = string,
  TAccountVaultAta extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
    'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountSystemProgram extends string | AccountMeta<string> =
    '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountOwnerAta extends string
        ? WritableAccount<TAccountOwnerAta>
        : TAccountOwnerAta,
      TAccountVaultAta extends string
        ? WritableAccount<TAccountVaultAta>
        : TAccountVaultAta,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseVaultInstructionData = { discriminator: ReadonlyUint8Array };

export type CloseVaultInstructionDataArgs = {};

export function getCloseVaultInstructionDataEncoder(): FixedSizeEncoder<CloseVaultInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_VAULT_DISCRIMINATOR })
  );
}

export function getCloseVaultInstructionDataDecoder(): FixedSizeDecoder<CloseVaultInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseVaultInstructionDataCodec(): FixedSizeCodec<
  CloseVaultInstructionDataArgs,
  CloseVaultInstructionData
> {
  return combineCodec(
    getCloseVaultInstructionDataEncoder(),
    getCloseVaultInstructionDataDecoder()
  );
}

export type CloseVaultAsyncInput<
  TAccountOwner extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountOwnerAta extends string = string,
  TAccountVaultAta extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The vault owner — signs the transaction and reclaims all tokens + rent. */
  owner: TransactionSigner<TAccountOwner>;
  vault: Address<TAccountVault>;
  /**
   * The SPL token mint that was staked.
   * Validated implicitly via `has_one = mint` on the vault above.
   */
  mint: Address<TAccountMint>;
  /**
   * Owner's Associated Token Account — receives the staked tokens back.
   * `init_if_needed` handles the rare edge-case where the owner closed
   * their ATA after the vault was initialized.
   */
  ownerAta?: Address<TAccountOwnerAta>;
  /**
   * Vault's Associated Token Account — holds the staked tokens.
   * Anchor validates the address matches (vault PDA, mint).
   * The vault PDA is the sole authority; only PDA-signed CPIs can move tokens.
   */
  vaultAta?: Address<TAccountVaultAta>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getCloseVaultInstructionAsync<
  TAccountOwner extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountOwnerAta extends string,
  TAccountVaultAta extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PROOF_POL_PROGRAM_ADDRESS,
>(
  input: CloseVaultAsyncInput<
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CloseVaultInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PROOF_POL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    ownerAta: { value: input.ownerAta ?? null, isWritable: true },
    vaultAta: { value: input.vaultAta ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.ownerAta.value) {
    accounts.ownerAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.vaultAta.value) {
    accounts.vaultAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.ownerAta),
      getAccountMeta(accounts.vaultAta),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCloseVaultInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseVaultInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type CloseVaultInput<
  TAccountOwner extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountOwnerAta extends string = string,
  TAccountVaultAta extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The vault owner — signs the transaction and reclaims all tokens + rent. */
  owner: TransactionSigner<TAccountOwner>;
  vault: Address<TAccountVault>;
  /**
   * The SPL token mint that was staked.
   * Validated implicitly via `has_one = mint` on the vault above.
   */
  mint: Address<TAccountMint>;
  /**
   * Owner's Associated Token Account — receives the staked tokens back.
   * `init_if_needed` handles the rare edge-case where the owner closed
   * their ATA after the vault was initialized.
   */
  ownerAta: Address<TAccountOwnerAta>;
  /**
   * Vault's Associated Token Account — holds the staked tokens.
   * Anchor validates the address matches (vault PDA, mint).
   * The vault PDA is the sole authority; only PDA-signed CPIs can move tokens.
   */
  vaultAta: Address<TAccountVaultAta>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getCloseVaultInstruction<
  TAccountOwner extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountOwnerAta extends string,
  TAccountVaultAta extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PROOF_POL_PROGRAM_ADDRESS,
>(
  input: CloseVaultInput<
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CloseVaultInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountVault,
  TAccountMint,
  TAccountOwnerAta,
  TAccountVaultAta,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PROOF_POL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    ownerAta: { value: input.ownerAta ?? null, isWritable: true },
    vaultAta: { value: input.vaultAta ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.ownerAta),
      getAccountMeta(accounts.vaultAta),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCloseVaultInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseVaultInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedCloseVaultInstruction<
  TProgram extends string = typeof PROOF_POL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The vault owner — signs the transaction and reclaims all tokens + rent. */
    owner: TAccountMetas[0];
    vault: TAccountMetas[1];
    /**
     * The SPL token mint that was staked.
     * Validated implicitly via `has_one = mint` on the vault above.
     */
    mint: TAccountMetas[2];
    /**
     * Owner's Associated Token Account — receives the staked tokens back.
     * `init_if_needed` handles the rare edge-case where the owner closed
     * their ATA after the vault was initialized.
     */
    ownerAta: TAccountMetas[3];
    /**
     * Vault's Associated Token Account — holds the staked tokens.
     * Anchor validates the address matches (vault PDA, mint).
     * The vault PDA is the sole authority; only PDA-signed CPIs can move tokens.
     */
    vaultAta: TAccountMetas[4];
    tokenProgram: TAccountMetas[5];
    associatedTokenProgram: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
  };
  data: CloseVaultInstructionData;
};

export function parseCloseVaultInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCloseVaultInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      vault: getNextAccount(),
      mint: getNextAccount(),
      ownerAta: getNextAccount(),
      vaultAta: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCloseVaultInstructionDataDecoder().decode(instruction.data),
  };
}
