/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { PROOF_POL_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const INITIALIZE_VAULT_DISCRIMINATOR = new Uint8Array([
  48, 191, 163, 44, 71, 129, 63, 164,
]);

export function getInitializeVaultDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_VAULT_DISCRIMINATOR
  );
}

export type InitializeVaultInstruction<
  TProgram extends string = typeof PROOF_POL_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountNominee extends string | AccountMeta<string> = string,
  TAccountOwnerProfile extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountOwnerAta extends string | AccountMeta<string> = string,
  TAccountVaultAta extends string | AccountMeta<string> = string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountOwnerUsdcAta extends string | AccountMeta<string> = string,
  TAccountPlatformWallet extends string | AccountMeta<string> =
    '99xMByFHuyHspBCeygNAMya9jixwb2RsMsM4AQKefn2q',
  TAccountPlatformUsdcAta extends string | AccountMeta<string> = string,
  TAccountVaultKTokenAta extends string | AccountMeta<string> = string,
  TAccountKTokenMint extends string | AccountMeta<string> = string,
  TAccountKaminoReserve extends string | AccountMeta<string> = string,
  TAccountKaminoLendingMarket extends string | AccountMeta<string> = string,
  TAccountKaminoLendingMarketAuthority extends string | AccountMeta<string> =
    string,
  TAccountKaminoLiquiditySupply extends string | AccountMeta<string> = string,
  TAccountKaminoLendingProgram extends string | AccountMeta<string> = string,
  TAccountInstructionSysvar extends string | AccountMeta<string> =
    'Sysvar1nstructions1111111111111111111111111',
  TAccountTokenProgram extends string | AccountMeta<string> =
    'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
    'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountSystemProgram extends string | AccountMeta<string> =
    '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountNominee extends string
        ? ReadonlyAccount<TAccountNominee>
        : TAccountNominee,
      TAccountOwnerProfile extends string
        ? WritableAccount<TAccountOwnerProfile>
        : TAccountOwnerProfile,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountOwnerAta extends string
        ? WritableAccount<TAccountOwnerAta>
        : TAccountOwnerAta,
      TAccountVaultAta extends string
        ? WritableAccount<TAccountVaultAta>
        : TAccountVaultAta,
      TAccountUsdcMint extends string
        ? ReadonlyAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountOwnerUsdcAta extends string
        ? WritableAccount<TAccountOwnerUsdcAta>
        : TAccountOwnerUsdcAta,
      TAccountPlatformWallet extends string
        ? ReadonlyAccount<TAccountPlatformWallet>
        : TAccountPlatformWallet,
      TAccountPlatformUsdcAta extends string
        ? WritableAccount<TAccountPlatformUsdcAta>
        : TAccountPlatformUsdcAta,
      TAccountVaultKTokenAta extends string
        ? WritableAccount<TAccountVaultKTokenAta>
        : TAccountVaultKTokenAta,
      TAccountKTokenMint extends string
        ? ReadonlyAccount<TAccountKTokenMint>
        : TAccountKTokenMint,
      TAccountKaminoReserve extends string
        ? WritableAccount<TAccountKaminoReserve>
        : TAccountKaminoReserve,
      TAccountKaminoLendingMarket extends string
        ? ReadonlyAccount<TAccountKaminoLendingMarket>
        : TAccountKaminoLendingMarket,
      TAccountKaminoLendingMarketAuthority extends string
        ? ReadonlyAccount<TAccountKaminoLendingMarketAuthority>
        : TAccountKaminoLendingMarketAuthority,
      TAccountKaminoLiquiditySupply extends string
        ? WritableAccount<TAccountKaminoLiquiditySupply>
        : TAccountKaminoLiquiditySupply,
      TAccountKaminoLendingProgram extends string
        ? ReadonlyAccount<TAccountKaminoLendingProgram>
        : TAccountKaminoLendingProgram,
      TAccountInstructionSysvar extends string
        ? ReadonlyAccount<TAccountInstructionSysvar>
        : TAccountInstructionSysvar,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeVaultInstructionData = {
  discriminator: ReadonlyUint8Array;
  vaultId: bigint;
  stakeAmount: bigint;
  checkinInterval: bigint;
};

export type InitializeVaultInstructionDataArgs = {
  vaultId: number | bigint;
  stakeAmount: number | bigint;
  checkinInterval: number | bigint;
};

export function getInitializeVaultInstructionDataEncoder(): FixedSizeEncoder<InitializeVaultInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['vaultId', getU64Encoder()],
      ['stakeAmount', getU64Encoder()],
      ['checkinInterval', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_VAULT_DISCRIMINATOR })
  );
}

export function getInitializeVaultInstructionDataDecoder(): FixedSizeDecoder<InitializeVaultInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['vaultId', getU64Decoder()],
    ['stakeAmount', getU64Decoder()],
    ['checkinInterval', getU64Decoder()],
  ]);
}

export function getInitializeVaultInstructionDataCodec(): FixedSizeCodec<
  InitializeVaultInstructionDataArgs,
  InitializeVaultInstructionData
> {
  return combineCodec(
    getInitializeVaultInstructionDataEncoder(),
    getInitializeVaultInstructionDataDecoder()
  );
}

export type InitializeVaultAsyncInput<
  TAccountOwner extends string = string,
  TAccountNominee extends string = string,
  TAccountOwnerProfile extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountOwnerAta extends string = string,
  TAccountVaultAta extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountOwnerUsdcAta extends string = string,
  TAccountPlatformWallet extends string = string,
  TAccountPlatformUsdcAta extends string = string,
  TAccountVaultKTokenAta extends string = string,
  TAccountKTokenMint extends string = string,
  TAccountKaminoReserve extends string = string,
  TAccountKaminoLendingMarket extends string = string,
  TAccountKaminoLendingMarketAuthority extends string = string,
  TAccountKaminoLiquiditySupply extends string = string,
  TAccountKaminoLendingProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  nominee: Address<TAccountNominee>;
  ownerProfile?: Address<TAccountOwnerProfile>;
  /** PDA vault state account. */
  vault?: Address<TAccountVault>;
  /** The SPL token mint being staked (USDC or wSOL on mainnet). */
  mint: Address<TAccountMint>;
  /** Owner's token ATA — tokens are pulled from here. */
  ownerAta?: Address<TAccountOwnerAta>;
  /**
   * Vault's token ATA — holds tokens on devnet; used as staging on mainnet
   * before the Kamino CPI moves them into the reserve.
   */
  vaultAta?: Address<TAccountVaultAta>;
  usdcMint: Address<TAccountUsdcMint>;
  ownerUsdcAta?: Address<TAccountOwnerUsdcAta>;
  platformWallet?: Address<TAccountPlatformWallet>;
  platformUsdcAta?: Address<TAccountPlatformUsdcAta>;
  /**
   * Vault's kToken ATA — receives Kamino receipt tokens on mainnet.
   * Created here so the ATA exists. On devnet it stays empty.
   */
  vaultKTokenAta?: Address<TAccountVaultKTokenAta>;
  /**
   * Kamino collateral/receipt token mint (kUSDC or kSOL on mainnet).
   * On devnet: pass `mint` itself as a placeholder.
   */
  kTokenMint: Address<TAccountKTokenMint>;
  /** Kamino reserve for the deposited token. */
  kaminoReserve: Address<TAccountKaminoReserve>;
  kaminoLendingMarket: Address<TAccountKaminoLendingMarket>;
  kaminoLendingMarketAuthority: Address<TAccountKaminoLendingMarketAuthority>;
  /** Kamino liquidity supply vault (receives the actual tokens). */
  kaminoLiquiditySupply: Address<TAccountKaminoLiquiditySupply>;
  kaminoLendingProgram: Address<TAccountKaminoLendingProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  vaultId: InitializeVaultInstructionDataArgs['vaultId'];
  stakeAmount: InitializeVaultInstructionDataArgs['stakeAmount'];
  checkinInterval: InitializeVaultInstructionDataArgs['checkinInterval'];
};

export async function getInitializeVaultInstructionAsync<
  TAccountOwner extends string,
  TAccountNominee extends string,
  TAccountOwnerProfile extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountOwnerAta extends string,
  TAccountVaultAta extends string,
  TAccountUsdcMint extends string,
  TAccountOwnerUsdcAta extends string,
  TAccountPlatformWallet extends string,
  TAccountPlatformUsdcAta extends string,
  TAccountVaultKTokenAta extends string,
  TAccountKTokenMint extends string,
  TAccountKaminoReserve extends string,
  TAccountKaminoLendingMarket extends string,
  TAccountKaminoLendingMarketAuthority extends string,
  TAccountKaminoLiquiditySupply extends string,
  TAccountKaminoLendingProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PROOF_POL_PROGRAM_ADDRESS,
>(
  input: InitializeVaultAsyncInput<
    TAccountOwner,
    TAccountNominee,
    TAccountOwnerProfile,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountUsdcMint,
    TAccountOwnerUsdcAta,
    TAccountPlatformWallet,
    TAccountPlatformUsdcAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitializeVaultInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountNominee,
    TAccountOwnerProfile,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountUsdcMint,
    TAccountOwnerUsdcAta,
    TAccountPlatformWallet,
    TAccountPlatformUsdcAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PROOF_POL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    nominee: { value: input.nominee ?? null, isWritable: false },
    ownerProfile: { value: input.ownerProfile ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    ownerAta: { value: input.ownerAta ?? null, isWritable: true },
    vaultAta: { value: input.vaultAta ?? null, isWritable: true },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    ownerUsdcAta: { value: input.ownerUsdcAta ?? null, isWritable: true },
    platformWallet: { value: input.platformWallet ?? null, isWritable: false },
    platformUsdcAta: { value: input.platformUsdcAta ?? null, isWritable: true },
    vaultKTokenAta: { value: input.vaultKTokenAta ?? null, isWritable: true },
    kTokenMint: { value: input.kTokenMint ?? null, isWritable: false },
    kaminoReserve: { value: input.kaminoReserve ?? null, isWritable: true },
    kaminoLendingMarket: {
      value: input.kaminoLendingMarket ?? null,
      isWritable: false,
    },
    kaminoLendingMarketAuthority: {
      value: input.kaminoLendingMarketAuthority ?? null,
      isWritable: false,
    },
    kaminoLiquiditySupply: {
      value: input.kaminoLiquiditySupply ?? null,
      isWritable: true,
    },
    kaminoLendingProgram: {
      value: input.kaminoLendingProgram ?? null,
      isWritable: false,
    },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.ownerProfile.value) {
    accounts.ownerProfile.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            111, 119, 110, 101, 114, 95, 112, 114, 111, 102, 105, 108, 101,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
      ],
    });
  }
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getU64Encoder().encode(expectSome(args.vaultId)),
      ],
    });
  }
  if (!accounts.ownerAta.value) {
    accounts.ownerAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.vaultAta.value) {
    accounts.vaultAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.ownerUsdcAta.value) {
    accounts.ownerUsdcAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.usdcMint.value)),
      ],
    });
  }
  if (!accounts.platformWallet.value) {
    accounts.platformWallet.value =
      '99xMByFHuyHspBCeygNAMya9jixwb2RsMsM4AQKefn2q' as Address<'99xMByFHuyHspBCeygNAMya9jixwb2RsMsM4AQKefn2q'>;
  }
  if (!accounts.platformUsdcAta.value) {
    accounts.platformUsdcAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.platformWallet.value)
        ),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.usdcMint.value)),
      ],
    });
  }
  if (!accounts.vaultKTokenAta.value) {
    accounts.vaultKTokenAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.vault.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.kTokenMint.value)),
      ],
    });
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      'Sysvar1nstructions1111111111111111111111111' as Address<'Sysvar1nstructions1111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.nominee),
      getAccountMeta(accounts.ownerProfile),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.ownerAta),
      getAccountMeta(accounts.vaultAta),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.ownerUsdcAta),
      getAccountMeta(accounts.platformWallet),
      getAccountMeta(accounts.platformUsdcAta),
      getAccountMeta(accounts.vaultKTokenAta),
      getAccountMeta(accounts.kTokenMint),
      getAccountMeta(accounts.kaminoReserve),
      getAccountMeta(accounts.kaminoLendingMarket),
      getAccountMeta(accounts.kaminoLendingMarketAuthority),
      getAccountMeta(accounts.kaminoLiquiditySupply),
      getAccountMeta(accounts.kaminoLendingProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeVaultInstructionDataEncoder().encode(
      args as InitializeVaultInstructionDataArgs
    ),
    programAddress,
  } as InitializeVaultInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountNominee,
    TAccountOwnerProfile,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountUsdcMint,
    TAccountOwnerUsdcAta,
    TAccountPlatformWallet,
    TAccountPlatformUsdcAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type InitializeVaultInput<
  TAccountOwner extends string = string,
  TAccountNominee extends string = string,
  TAccountOwnerProfile extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountOwnerAta extends string = string,
  TAccountVaultAta extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountOwnerUsdcAta extends string = string,
  TAccountPlatformWallet extends string = string,
  TAccountPlatformUsdcAta extends string = string,
  TAccountVaultKTokenAta extends string = string,
  TAccountKTokenMint extends string = string,
  TAccountKaminoReserve extends string = string,
  TAccountKaminoLendingMarket extends string = string,
  TAccountKaminoLendingMarketAuthority extends string = string,
  TAccountKaminoLiquiditySupply extends string = string,
  TAccountKaminoLendingProgram extends string = string,
  TAccountInstructionSysvar extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  nominee: Address<TAccountNominee>;
  ownerProfile: Address<TAccountOwnerProfile>;
  /** PDA vault state account. */
  vault: Address<TAccountVault>;
  /** The SPL token mint being staked (USDC or wSOL on mainnet). */
  mint: Address<TAccountMint>;
  /** Owner's token ATA — tokens are pulled from here. */
  ownerAta: Address<TAccountOwnerAta>;
  /**
   * Vault's token ATA — holds tokens on devnet; used as staging on mainnet
   * before the Kamino CPI moves them into the reserve.
   */
  vaultAta: Address<TAccountVaultAta>;
  usdcMint: Address<TAccountUsdcMint>;
  ownerUsdcAta: Address<TAccountOwnerUsdcAta>;
  platformWallet?: Address<TAccountPlatformWallet>;
  platformUsdcAta: Address<TAccountPlatformUsdcAta>;
  /**
   * Vault's kToken ATA — receives Kamino receipt tokens on mainnet.
   * Created here so the ATA exists. On devnet it stays empty.
   */
  vaultKTokenAta: Address<TAccountVaultKTokenAta>;
  /**
   * Kamino collateral/receipt token mint (kUSDC or kSOL on mainnet).
   * On devnet: pass `mint` itself as a placeholder.
   */
  kTokenMint: Address<TAccountKTokenMint>;
  /** Kamino reserve for the deposited token. */
  kaminoReserve: Address<TAccountKaminoReserve>;
  kaminoLendingMarket: Address<TAccountKaminoLendingMarket>;
  kaminoLendingMarketAuthority: Address<TAccountKaminoLendingMarketAuthority>;
  /** Kamino liquidity supply vault (receives the actual tokens). */
  kaminoLiquiditySupply: Address<TAccountKaminoLiquiditySupply>;
  kaminoLendingProgram: Address<TAccountKaminoLendingProgram>;
  instructionSysvar?: Address<TAccountInstructionSysvar>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  vaultId: InitializeVaultInstructionDataArgs['vaultId'];
  stakeAmount: InitializeVaultInstructionDataArgs['stakeAmount'];
  checkinInterval: InitializeVaultInstructionDataArgs['checkinInterval'];
};

export function getInitializeVaultInstruction<
  TAccountOwner extends string,
  TAccountNominee extends string,
  TAccountOwnerProfile extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountOwnerAta extends string,
  TAccountVaultAta extends string,
  TAccountUsdcMint extends string,
  TAccountOwnerUsdcAta extends string,
  TAccountPlatformWallet extends string,
  TAccountPlatformUsdcAta extends string,
  TAccountVaultKTokenAta extends string,
  TAccountKTokenMint extends string,
  TAccountKaminoReserve extends string,
  TAccountKaminoLendingMarket extends string,
  TAccountKaminoLendingMarketAuthority extends string,
  TAccountKaminoLiquiditySupply extends string,
  TAccountKaminoLendingProgram extends string,
  TAccountInstructionSysvar extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PROOF_POL_PROGRAM_ADDRESS,
>(
  input: InitializeVaultInput<
    TAccountOwner,
    TAccountNominee,
    TAccountOwnerProfile,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountUsdcMint,
    TAccountOwnerUsdcAta,
    TAccountPlatformWallet,
    TAccountPlatformUsdcAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeVaultInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountNominee,
  TAccountOwnerProfile,
  TAccountVault,
  TAccountMint,
  TAccountOwnerAta,
  TAccountVaultAta,
  TAccountUsdcMint,
  TAccountOwnerUsdcAta,
  TAccountPlatformWallet,
  TAccountPlatformUsdcAta,
  TAccountVaultKTokenAta,
  TAccountKTokenMint,
  TAccountKaminoReserve,
  TAccountKaminoLendingMarket,
  TAccountKaminoLendingMarketAuthority,
  TAccountKaminoLiquiditySupply,
  TAccountKaminoLendingProgram,
  TAccountInstructionSysvar,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PROOF_POL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    nominee: { value: input.nominee ?? null, isWritable: false },
    ownerProfile: { value: input.ownerProfile ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    ownerAta: { value: input.ownerAta ?? null, isWritable: true },
    vaultAta: { value: input.vaultAta ?? null, isWritable: true },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    ownerUsdcAta: { value: input.ownerUsdcAta ?? null, isWritable: true },
    platformWallet: { value: input.platformWallet ?? null, isWritable: false },
    platformUsdcAta: { value: input.platformUsdcAta ?? null, isWritable: true },
    vaultKTokenAta: { value: input.vaultKTokenAta ?? null, isWritable: true },
    kTokenMint: { value: input.kTokenMint ?? null, isWritable: false },
    kaminoReserve: { value: input.kaminoReserve ?? null, isWritable: true },
    kaminoLendingMarket: {
      value: input.kaminoLendingMarket ?? null,
      isWritable: false,
    },
    kaminoLendingMarketAuthority: {
      value: input.kaminoLendingMarketAuthority ?? null,
      isWritable: false,
    },
    kaminoLiquiditySupply: {
      value: input.kaminoLiquiditySupply ?? null,
      isWritable: true,
    },
    kaminoLendingProgram: {
      value: input.kaminoLendingProgram ?? null,
      isWritable: false,
    },
    instructionSysvar: {
      value: input.instructionSysvar ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.platformWallet.value) {
    accounts.platformWallet.value =
      '99xMByFHuyHspBCeygNAMya9jixwb2RsMsM4AQKefn2q' as Address<'99xMByFHuyHspBCeygNAMya9jixwb2RsMsM4AQKefn2q'>;
  }
  if (!accounts.instructionSysvar.value) {
    accounts.instructionSysvar.value =
      'Sysvar1nstructions1111111111111111111111111' as Address<'Sysvar1nstructions1111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.nominee),
      getAccountMeta(accounts.ownerProfile),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.ownerAta),
      getAccountMeta(accounts.vaultAta),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.ownerUsdcAta),
      getAccountMeta(accounts.platformWallet),
      getAccountMeta(accounts.platformUsdcAta),
      getAccountMeta(accounts.vaultKTokenAta),
      getAccountMeta(accounts.kTokenMint),
      getAccountMeta(accounts.kaminoReserve),
      getAccountMeta(accounts.kaminoLendingMarket),
      getAccountMeta(accounts.kaminoLendingMarketAuthority),
      getAccountMeta(accounts.kaminoLiquiditySupply),
      getAccountMeta(accounts.kaminoLendingProgram),
      getAccountMeta(accounts.instructionSysvar),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeVaultInstructionDataEncoder().encode(
      args as InitializeVaultInstructionDataArgs
    ),
    programAddress,
  } as InitializeVaultInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountNominee,
    TAccountOwnerProfile,
    TAccountVault,
    TAccountMint,
    TAccountOwnerAta,
    TAccountVaultAta,
    TAccountUsdcMint,
    TAccountOwnerUsdcAta,
    TAccountPlatformWallet,
    TAccountPlatformUsdcAta,
    TAccountVaultKTokenAta,
    TAccountKTokenMint,
    TAccountKaminoReserve,
    TAccountKaminoLendingMarket,
    TAccountKaminoLendingMarketAuthority,
    TAccountKaminoLiquiditySupply,
    TAccountKaminoLendingProgram,
    TAccountInstructionSysvar,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeVaultInstruction<
  TProgram extends string = typeof PROOF_POL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    nominee: TAccountMetas[1];
    ownerProfile: TAccountMetas[2];
    /** PDA vault state account. */
    vault: TAccountMetas[3];
    /** The SPL token mint being staked (USDC or wSOL on mainnet). */
    mint: TAccountMetas[4];
    /** Owner's token ATA — tokens are pulled from here. */
    ownerAta: TAccountMetas[5];
    /**
     * Vault's token ATA — holds tokens on devnet; used as staging on mainnet
     * before the Kamino CPI moves them into the reserve.
     */
    vaultAta: TAccountMetas[6];
    usdcMint: TAccountMetas[7];
    ownerUsdcAta: TAccountMetas[8];
    platformWallet: TAccountMetas[9];
    platformUsdcAta: TAccountMetas[10];
    /**
     * Vault's kToken ATA — receives Kamino receipt tokens on mainnet.
     * Created here so the ATA exists. On devnet it stays empty.
     */
    vaultKTokenAta: TAccountMetas[11];
    /**
     * Kamino collateral/receipt token mint (kUSDC or kSOL on mainnet).
     * On devnet: pass `mint` itself as a placeholder.
     */
    kTokenMint: TAccountMetas[12];
    /** Kamino reserve for the deposited token. */
    kaminoReserve: TAccountMetas[13];
    kaminoLendingMarket: TAccountMetas[14];
    kaminoLendingMarketAuthority: TAccountMetas[15];
    /** Kamino liquidity supply vault (receives the actual tokens). */
    kaminoLiquiditySupply: TAccountMetas[16];
    kaminoLendingProgram: TAccountMetas[17];
    instructionSysvar: TAccountMetas[18];
    tokenProgram: TAccountMetas[19];
    associatedTokenProgram: TAccountMetas[20];
    systemProgram: TAccountMetas[21];
  };
  data: InitializeVaultInstructionData;
};

export function parseInitializeVaultInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeVaultInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 22) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      nominee: getNextAccount(),
      ownerProfile: getNextAccount(),
      vault: getNextAccount(),
      mint: getNextAccount(),
      ownerAta: getNextAccount(),
      vaultAta: getNextAccount(),
      usdcMint: getNextAccount(),
      ownerUsdcAta: getNextAccount(),
      platformWallet: getNextAccount(),
      platformUsdcAta: getNextAccount(),
      vaultKTokenAta: getNextAccount(),
      kTokenMint: getNextAccount(),
      kaminoReserve: getNextAccount(),
      kaminoLendingMarket: getNextAccount(),
      kaminoLendingMarketAuthority: getNextAccount(),
      kaminoLiquiditySupply: getNextAccount(),
      kaminoLendingProgram: getNextAccount(),
      instructionSysvar: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeVaultInstructionDataDecoder().decode(instruction.data),
  };
}
