/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { PROOF_POL_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const PROOF_OF_LIFE_DISCRIMINATOR = new Uint8Array([
  52, 157, 123, 29, 44, 147, 143, 234,
]);

export function getProofOfLifeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PROOF_OF_LIFE_DISCRIMINATOR
  );
}

export type ProofOfLifeInstruction<
  TProgram extends string = typeof PROOF_POL_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      ...TRemainingAccounts,
    ]
  >;

export type ProofOfLifeInstructionData = { discriminator: ReadonlyUint8Array };

export type ProofOfLifeInstructionDataArgs = {};

export function getProofOfLifeInstructionDataEncoder(): FixedSizeEncoder<ProofOfLifeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: PROOF_OF_LIFE_DISCRIMINATOR })
  );
}

export function getProofOfLifeInstructionDataDecoder(): FixedSizeDecoder<ProofOfLifeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getProofOfLifeInstructionDataCodec(): FixedSizeCodec<
  ProofOfLifeInstructionDataArgs,
  ProofOfLifeInstructionData
> {
  return combineCodec(
    getProofOfLifeInstructionDataEncoder(),
    getProofOfLifeInstructionDataDecoder()
  );
}

export type ProofOfLifeAsyncInput<
  TAccountOwner extends string = string,
  TAccountVault extends string = string,
> = {
  /** The vault owner - must sign to prove they are alive. */
  owner: TransactionSigner<TAccountOwner>;
  vault?: Address<TAccountVault>;
};

export async function getProofOfLifeInstructionAsync<
  TAccountOwner extends string,
  TAccountVault extends string,
  TProgramAddress extends Address = typeof PROOF_POL_PROGRAM_ADDRESS,
>(
  input: ProofOfLifeAsyncInput<TAccountOwner, TAccountVault>,
  config?: { programAddress?: TProgramAddress }
): Promise<
  ProofOfLifeInstruction<TProgramAddress, TAccountOwner, TAccountVault>
> {
  // Program address.
  const programAddress = config?.programAddress ?? PROOF_POL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
        getAddressEncoder().encode(expectAddress(accounts.owner.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [getAccountMeta(accounts.owner), getAccountMeta(accounts.vault)],
    data: getProofOfLifeInstructionDataEncoder().encode({}),
    programAddress,
  } as ProofOfLifeInstruction<TProgramAddress, TAccountOwner, TAccountVault>);
}

export type ProofOfLifeInput<
  TAccountOwner extends string = string,
  TAccountVault extends string = string,
> = {
  /** The vault owner - must sign to prove they are alive. */
  owner: TransactionSigner<TAccountOwner>;
  vault: Address<TAccountVault>;
};

export function getProofOfLifeInstruction<
  TAccountOwner extends string,
  TAccountVault extends string,
  TProgramAddress extends Address = typeof PROOF_POL_PROGRAM_ADDRESS,
>(
  input: ProofOfLifeInput<TAccountOwner, TAccountVault>,
  config?: { programAddress?: TProgramAddress }
): ProofOfLifeInstruction<TProgramAddress, TAccountOwner, TAccountVault> {
  // Program address.
  const programAddress = config?.programAddress ?? PROOF_POL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [getAccountMeta(accounts.owner), getAccountMeta(accounts.vault)],
    data: getProofOfLifeInstructionDataEncoder().encode({}),
    programAddress,
  } as ProofOfLifeInstruction<TProgramAddress, TAccountOwner, TAccountVault>);
}

export type ParsedProofOfLifeInstruction<
  TProgram extends string = typeof PROOF_POL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The vault owner - must sign to prove they are alive. */
    owner: TAccountMetas[0];
    vault: TAccountMetas[1];
  };
  data: ProofOfLifeInstructionData;
};

export function parseProofOfLifeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedProofOfLifeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { owner: getNextAccount(), vault: getNextAccount() },
    data: getProofOfLifeInstructionDataDecoder().decode(instruction.data),
  };
}
